name = "app-thales"
compatibility_date = "2026-04-16"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "app-thales-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
preview_database_id = "REPLACE_WITH_YOUR_D1_PREVIEW_DATABASE_ID"
