name = "app-thales"
compatibility_date = "2026-04-16"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "app-thales-db"
database_id = "9cf80abf-425a-4291-b97f-f18fd84dd77b"
preview_database_id = "9cf80abf-425a-4291-b97f-f18fd84dd77b"
